### ISSUE TITLE
ClamAV is only working for version 11 of Nextcloud.

### ISSUE THREAD

**Issue by poisony** [nextcloud/files_antivirus#1]
ClamAV is only working for version 11 of Nextcloud.

I can't get it to work with NextCloud 10? :(

**Comment by SomeStrangeName** [comment]
I noticed the plugin/app is completely missing in nextcloud 10 (can't find the files_antivirus folder) but it is mentioned in the documentation.

I just did an upgrade from owncloud 9.1 to nextcloud 10 today and was not so happy about the missing antivirus.

**Comment by nickvergessen** [comment]
@LukasReschke

**Comment by SomeStrangeName** [comment]
I figured out that copy the old files_antivirus folder form my old owncloud 9.1 installation (done on Debain with package manager) seems working.
During a short test I discovered that a file will only be checked during initial upload but not if it is touched.
You can test like this, create a text file with the EICAR string https://en.wikipedia.org/wiki/EICAR_test_file and upload. Afterwards configure Clamav. Rename the file -> nothing happens. Copy&Paste the file, now the check will be done.

Could be a good idea to start a full run (maybe optional) during initial activation of the app.
Could also be a good idea to be able to trigger full scans (since files may contain undetected viruses but newer signatures are available).

**Comment by nickvergessen** [comment]
Yeah we don't bundle that app, just like calendar and contacts you need to download them manually.

**Comment by SomeStrangeName** [comment]
Would be nice to have it as default app. Anyhow at least current documentation how to install it should be updated. See https://docs.nextcloud.com/server/9/admin_manual/configuration_server/antivirus_configuration.html (seems to be a copy of owncloud doc).

**Comment by arjanvs** [comment]
Indeed weird, that it is not part of the core. Because, I find security an important feature of a cloud. I do not want virusses go viral.

I like to refer also to: [https://github.com/nextcloud/server/issues/1445](https://github.com/nextcloud/server/issues/1445). For me it very unclear, without reading this thread, how to install the files_antivirus app.

**Comment by JK74** [comment]
clamav is nog find yet in NC12 apps is that still work in progress or not progressing? cheers!
